# SPDX-License-Identifier: GPL-2.0-only

dtb-$(TARGET_ARM32) += \
	stm32mp251f-ev1-ca35tdcid-ostl.dtb

dtb-$(TARGET_ARM64) += \
	stm32mp257f-ev1-ca35tdcid-ostl.dtb \
	stm32mp257f-ev1-ca35tdcid-ostl-m33-examples.dtb \
	stm32mp257f-ev1-ca35tdcid-ostl-m33-examples-sram.dtb \
	stm32mp257f-ev1-psci-osi.dtb \
	stm32mp257f-ev1-tampers.dtb \
	stm32mp257f-dk-ca35tdcid-ostl.dtb \
	stm32mp257f-dk-ca35tdcid-ostl-m33-examples.dtb \
	stm32mp215f-dk-ca35tdcid-ostl.dtb \
	stm32mp215f-dk-ca35tdcid-ostl-m33-examples.dtb \
	stm32mp215f-dk-psci-osi.dtb
