# SPDX-License-Identifier: GPL-2.0-only

dtb-$(TARGET_ARM32) += \

dtb-$(TARGET_ARM64) += \
	stm32mp215f-dk-cm33tdcid-ostl-sdcard.dtb \
	stm32mp257f-ev1-cm33tdcid-ostl-emmc.dtb \
	stm32mp257f-ev1-cm33tdcid-ostl-snor.dtb \
	stm32mp257f-ev1-cm33tdcid-ostl-sdcard.dtb
